Repository mash-up-kr/mash-up-admin-fe, pull requests merged in 2022-03, with the labels that each got.

#110 자잘한 버그 수정 및 합격 여부 상태 변경 모달(ChangeResultModalDialog) 구현
  src/api/application.ts
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx
  src/components/ApplicationDetail/MessageListPanel/MessageListPanel.component.tsx
  src/components/ApplicationDetail/MessageListPanel/MessageListPanel.styled.tsx
  src/components/ApplicationDetail/SmsSendModalDialog/SmsSendModalDialog.component.tsx
  src/components/ApplicationDetail/TitleWithContent/TitleWithContent.component.tsx
  src/components/common/AlertModalDialog/AlertModalDialog.component.tsx
  src/components/common/ModalViewer/ModalViewer.component.tsx
  src/components/common/ModalViewer/ModalViewer.stories.tsx
  src/components/common/ModalWrapper/ModalWrapper.component.tsx
  src/components/common/ModalWrapper/ModalWrapper.styled.ts
  src/components/common/PopOver/PopOver.styled.ts
  src/components/index.ts
  src/components/modal/ChangeResultModalDialog/ChangeResultModalDialog.component.tsx
  src/components/modal/ChangeResultModalDialog/ChangeResultModalDialog.stories.tsx
  src/components/modal/ChangeResultModalDialog/ChangeResultModalDialog.styled.tsx
  src/components/modal/index.ts
  src/pages/ApplicationFormDetail/ApplicationFormDetail.page.tsx
  src/pages/CreateApplicationForm/CreateApplicationForm.page.tsx
  src/pages/UpdateApplicationForm/UpdateApplicationForm.page.tsx
  src/store/modal.ts
  src/types/dto/application.ts
  src/types/dto/applicationById.ts
  src/types/dto/index.ts
Labels: bug, feature

#118 QA 2차 대응 (v0.0.1) - minsour
  src/components/common/Table/Table.styled.ts
Labels: bug

#117 Table 컴포넌트에 sort, select 기능 추가
  src/assets/svg/caret-up-16.svg
  src/assets/svg/caret-updown-16.svg
  src/components/common/Table/Table.component.tsx
  src/components/common/Table/Table.stories.tsx
  src/components/common/Table/Table.styled.ts
  src/constants/ui.ts
Labels: feature

#115 #110 개선사항 반영 및 Portal 언마운트 이슈 해결
  jest.config.js
  src/assets/svg/caret-up-16.svg
  src/assets/svg/caret-updown-16.svg
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.styled.ts
  src/components/ApplicationDetail/ApplicationQnAItem/ApplicationQnAItem.component.tsx
  src/components/ApplicationDetail/ApplicationQnAItem/ApplicationQnAItem.stories.tsx
  src/components/ApplicationDetail/MessageListPanel/MessageListPanel.component.tsx
  src/components/ApplicationDetail/SmsSendModalDialog/SmsSendModalDialog.component.tsx
  src/components/ApplicationDetail/SmsSendModalDialog/SmsSendModalDialog.styled.tsx
  src/components/ApplicationDetail/index.ts
  src/components/common/ModalViewer/ModalViewer.component.tsx
  src/components/common/ModalViewer/ModalViewer.stories.tsx
  src/components/common/ModalWrapper/ModalWrapper.component.tsx
  src/components/common/Pagination/PageButtonList/PageButtonList.test.tsx
  src/components/common/Portal/Portal.component.tsx
  src/components/common/SmsSendModalDialog/SmsSendModalDialog.component.tsx
  src/components/common/SmsSendModalDialog/SmsSendModalDialog.stories.tsx
  src/components/common/SmsSendModalDialog/SmsSendModalDialog.styled.tsx
  src/components/common/Table/Table.component.tsx
  src/components/common/Table/Table.stories.tsx
  src/components/common/Table/Table.styled.ts
  src/components/common/Table/Table.test.tsx
  src/components/common/Toast/Toast.component.tsx
  src/components/common/index.ts
  src/components/modal/ChangeResultModalDialog/ChangeResultModalDialog.component.tsx
  src/components/modal/MultipleSmsSendModalDialog/MultipleSmsSendModalDialog.component.tsx
  src/components/modal/MultipleSmsSendModalDialog/MultipleSmsSendModalDialog.stories.tsx
  src/components/modal/index.ts
  src/constants/ui.ts
  src/hooks/useMount.test.ts
  src/hooks/usePagination.test.ts
  src/pages/ApplicationDetailView/ApplicationDetailView.page.tsx
  src/pages/ApplicationFormDetail/ApplicationFormDetail.page.tsx
  src/pages/CreateApplicationForm/CreateApplicationForm.page.tsx
  src/pages/UpdateApplicationForm/UpdateApplicationForm.page.tsx
  src/store/modal.ts
  src/styles/themes/toast.ts
  src/styles/themes/userProfile.ts
  src/types/dto/application.ts
  src/types/dto/team.ts
  src/utils/request.ts
Labels: bug, refactor

#111 SMS 전송(여러명) 모달(SmsSendModalDialog) 기능 추가
  jest.config.js
  src/assets/svg/chevron-right-16.svg
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.styled.ts
  src/components/ApplicationDetail/ApplicationQnAItem/ApplicationQnAItem.component.tsx
  src/components/ApplicationDetail/ApplicationQnAItem/ApplicationQnAItem.stories.tsx
  src/components/ApplicationDetail/MessageListPanel/MessageListPanel.component.tsx
  src/components/ApplicationDetail/SmsSendModalDialog/SmsSendModalDialog.component.tsx
  src/components/ApplicationDetail/SmsSendModalDialog/SmsSendModalDialog.styled.tsx
  src/components/ApplicationDetail/index.ts
  src/components/common/ModalViewer/ModalViewer.component.tsx
  src/components/common/ModalViewer/ModalViewer.stories.tsx
  src/components/common/ModalWrapper/ModalWrapper.component.tsx
  src/components/common/Pagination/PageButtonList/PageButtonList.test.tsx
  src/components/common/Portal/Portal.component.tsx
  src/components/common/SmsSendModalDialog/SmsSendModalDialog.component.tsx
  src/components/common/SmsSendModalDialog/SmsSendModalDialog.stories.tsx
  src/components/common/SmsSendModalDialog/SmsSendModalDialog.styled.tsx
  src/components/common/Table/Table.test.tsx
  src/components/common/Toast/Toast.component.tsx
  src/components/common/index.ts
  src/components/modal/ChangeResultModalDialog/ChangeResultModalDialog.component.tsx
  src/hooks/useMount.test.ts
  src/hooks/usePagination.test.ts
  src/pages/ApplicationDetailView/ApplicationDetailView.page.tsx
  src/pages/ApplicationFormDetail/ApplicationFormDetail.page.tsx
  src/pages/CreateApplicationForm/CreateApplicationForm.page.tsx
  src/pages/UpdateApplicationForm/UpdateApplicationForm.page.tsx
  src/store/modal.ts
  src/styles/themes/toast.ts
  src/styles/themes/userProfile.ts
  src/types/dto/application.ts
  src/types/dto/team.ts
  src/utils/request.ts
Labels: feature

#124 지원서 미리보기 모달에 개인정보처리방침 url 추가
  src/components/ApplicationForm/ApplicationFormPreview/ApplicationFormPreview.component.tsx
  src/components/ApplicationForm/ApplicationFormPreview/ApplicationFormPreview.styled.ts
  src/components/common/Checkbox/Checkbox.component.tsx
Labels: feature

#125 글자수 제한 수정했을 때 지원서 폼 저장되지 않는 이슈 수정
  src/components/ApplicationForm/ApplicationFormItem/ApplicationFormItem.component.tsx
Labels: bug

#128 개인정보 처리방침 스타일 수정
  src/components/ApplicationForm/ApplicationFormPreview/ApplicationFormPreview.styled.ts
Labels: bug

#129 Qa Release/v0.0.1 - 5차
  src/components/ApplicationForm/ApplicationFormPreview/ApplicationFormPreview.styled.ts
Labels: deploy

#127 Real Release (v0.1.0)
  src/components/ApplicationForm/ApplicationFormItem/ApplicationFormItem.component.tsx
  src/components/ApplicationForm/ApplicationFormPreview/ApplicationFormPreview.component.tsx
  src/components/ApplicationForm/ApplicationFormPreview/ApplicationFormPreview.styled.ts
  src/components/common/Checkbox/Checkbox.component.tsx
Labels: deploy

#130 지원설문지 미리보기 생년월일, 거주지, 소속 필드 추가
  src/components/ApplicationForm/ApplicationFormPreview/ApplicationFormPreview.component.tsx
  src/components/ApplicationForm/ApplicationFormPreview/ApplicationFormPreview.styled.ts
Labels: feature

#132 Qa Release/v0.2.0
  src/components/ApplicationForm/ApplicationFormPreview/ApplicationFormPreview.component.tsx
  src/components/ApplicationForm/ApplicationFormPreview/ApplicationFormPreview.styled.ts
Labels: deploy

#133 Main Release/v0.2.0
  src/components/ApplicationForm/ApplicationFormPreview/ApplicationFormPreview.component.tsx
  src/components/ApplicationForm/ApplicationFormPreview/ApplicationFormPreview.styled.ts
Labels: deploy

#134 실행 안되는 에러 해결
  src/components/common/SmsSendModalDialog/SmsSendModalDialog.component.tsx
  src/components/common/SmsSendModalDialog/SmsSendModalDialog.styled.tsx
Labels: bug

#140 favicon, og-image 추가
  public/assets/favicon.svg
  public/assets/og-image.png
  public/index.html
  webpack/webpack.prod.js
Labels: feature

#135 지원설문지 상세 추가 작업 및 API 호출 막기
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx
  src/components/ApplicationDetail/ApplicationQnAItem/ApplicationQnAItem.component.tsx
  src/components/ApplicationDetail/ApplicationQnAItem/ApplicationQnAItem.stories.tsx
  src/components/ApplicationDetail/ApplicationQnAItem/ApplicationQnAItem.styled.ts
  src/components/ApplicationDetail/MessageListPanel/MessageListPanel.component.tsx
  src/components/ApplicationDetail/TitleWithContent/TitleWithContent.styled.ts
  src/components/common/SearchOptionBar/SearchOptionBar.component.tsx
  src/components/common/SearchOptionBar/SearchOptionBar.styled.ts
  src/components/common/Select/Select.component.tsx
  src/components/common/SmsSendModalDialog/SmsSendModalDialog.component.tsx
  src/pages/ApplicationDetailView/ApplicationDetailView.page.tsx
  src/pages/ApplicationDetailView/ApplicationDetailView.styled.ts
  src/types/dto/application.ts
  src/types/dto/applicationForm.ts
Labels: feature

#138 Application Page 추가
  src/App.tsx
  src/api/application.ts
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.stories.tsx
  src/components/common/ApplicationStatusBadge/ApplicationStatusBadge.component.tsx
  src/components/common/ApplicationStatusBadge/ApplicationStatusBadge.stories.tsx
  src/components/common/SearchOptionBar/SearchOptionBar.component.tsx
  src/components/common/Table/Table.component.tsx
  src/components/common/Table/Table.styled.ts
  src/components/common/TeamNavigationTabs/TeamNavigationTabs.component.tsx
  src/hooks/index.ts
  src/hooks/useDirty.ts
  src/pages/ApplicationFormList/ApplicationFormList.page.tsx
  src/pages/ApplicationList/ApplicationList.page.tsx
  src/pages/ApplicationList/ApplicationList.styled.ts
  src/pages/index.ts
  src/store/application.ts
  src/store/applicationForm.ts
  src/styles/resetCss.ts
  src/styles/themes/badge.ts
  src/types/dto/application.ts
Labels: feature

#143 Qa Release/v0.3.0
  public/index.html
Labels: deploy

#142 Main Release/v0.3.0
  public/assets/favicon.svg
  public/assets/og-image.png
  public/index.html
  src/App.tsx
  src/api/application.ts
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.stories.tsx
  src/components/ApplicationDetail/ApplicationQnAItem/ApplicationQnAItem.component.tsx
  src/components/ApplicationDetail/ApplicationQnAItem/ApplicationQnAItem.stories.tsx
  src/components/ApplicationDetail/ApplicationQnAItem/ApplicationQnAItem.styled.ts
  src/components/ApplicationDetail/MessageListPanel/MessageListPanel.component.tsx
  src/components/ApplicationDetail/TitleWithContent/TitleWithContent.styled.ts
  src/components/common/ApplicationStatusBadge/ApplicationStatusBadge.component.tsx
  src/components/common/ApplicationStatusBadge/ApplicationStatusBadge.stories.tsx
  src/components/common/SearchOptionBar/SearchOptionBar.component.tsx
  src/components/common/SearchOptionBar/SearchOptionBar.styled.ts
  src/components/common/Select/Select.component.tsx
  src/components/common/SmsSendModalDialog/SmsSendModalDialog.component.tsx
  src/components/common/Table/Table.component.tsx
  src/components/common/Table/Table.styled.ts
  src/components/common/TeamNavigationTabs/TeamNavigationTabs.component.tsx
  src/hooks/index.ts
  src/hooks/useDirty.ts
  src/pages/ApplicationDetailView/ApplicationDetailView.page.tsx
  src/pages/ApplicationDetailView/ApplicationDetailView.styled.ts
  src/pages/ApplicationFormList/ApplicationFormList.page.tsx
  src/pages/ApplicationList/ApplicationList.page.tsx
  src/pages/ApplicationList/ApplicationList.styled.ts
  src/pages/index.ts
  src/store/application.ts
  src/store/applicationForm.ts
  src/styles/resetCss.ts
  src/styles/themes/badge.ts
  src/types/dto/application.ts
  src/types/dto/applicationForm.ts
  webpack/webpack.prod.js
Labels: deploy

#144 필요한 커밋 revert 및 SmsSendModal 실패인원 재발송 케이스 추가
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx
  src/components/common/SmsSendModalDialog/SmsSendModalDialog.component.tsx
  src/components/common/SmsSendModalDialog/SmsSendModalDialog.stories.tsx
  src/components/common/SmsSendModalDialog/SmsSendModalDialog.styled.tsx
Labels: feature

#145 발송인원 상세 리스트, SMS 발송 상세내역 모달 다이얼로그 베이스 추가
  src/components/common/ModalViewer/ModalViewer.component.tsx
  src/components/common/ModalViewer/ModalViewer.stories.tsx
  src/components/common/SmsSendModalDialog/SmsSendModalDialog.component.tsx
  src/components/modal/SmsSendDetailInfoModalDialog/SmsSendDetailInfoModalDialog.component.tsx
  src/components/modal/SmsSendDetailInfoModalDialog/SmsSendDetailInfoModalDialog.stories.tsx
  src/components/modal/SmsSendDetailListModalDialog/SmsSendDetailListModalDialog.component.tsx
  src/components/modal/SmsSendDetailListModalDialog/SmsSendDetailListModalDialog.stories.tsx
  src/components/modal/index.ts
  src/store/modal.ts
Labels: feature

#146 지원설문지 상세 합격여부 Select를 SCREENING_PASSED 기준으로 validate
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.stories.tsx
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.styled.ts
Labels: feature

#147 ApplicationPanel의 예외사항을 고려하여 리팩토링
  src/api/application.ts
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.stories.tsx
  src/components/common/DatePicker/DatePicker.component.tsx
  src/components/common/DatePicker/DatePicker.stories.tsx
  src/types/dto/application.ts
Labels: feature

#148 문자 발송 API Body 에 잘못 들어간 값 변경
  src/components/ApplicationDetail/MessageListPanel/MessageListPanel.component.tsx
  src/components/common/SmsSendModalDialog/SmsSendModalDialog.component.tsx
  src/pages/ApplicationDetailView/ApplicationDetailView.page.tsx
  src/store/login.ts
  src/types/dto/adminMember.ts
Labels: bug

#149 지원서 내역 페이지에 일괄 합격여부 변경 모달 추가
  src/components/common/Table/Table.styled.ts
  src/pages/ApplicationList/ApplicationList.page.tsx
  src/pages/ApplicationList/ApplicationList.styled.ts
  src/utils/array.ts
Labels: feature

#150 지원 일시 기준을 updatedAt에서 submittedAt 으로 변경
  src/components/common/Table/Table.test.tsx
  src/pages/ApplicationDetailView/ApplicationDetailView.page.tsx
  src/pages/ApplicationList/ApplicationList.page.tsx
  src/types/dto/application.ts
Labels: bug

#151 Qa Release/v0.4.0 - 1차
  src/api/application.ts
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.stories.tsx
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.styled.ts
  src/components/ApplicationDetail/MessageListPanel/MessageListPanel.component.tsx
  src/components/common/DatePicker/DatePicker.component.tsx
  src/components/common/DatePicker/DatePicker.stories.tsx
  src/components/common/ModalViewer/ModalViewer.component.tsx
  src/components/common/ModalViewer/ModalViewer.stories.tsx
  src/components/common/SmsSendModalDialog/SmsSendModalDialog.component.tsx
  src/components/common/SmsSendModalDialog/SmsSendModalDialog.stories.tsx
  src/components/common/SmsSendModalDialog/SmsSendModalDialog.styled.tsx
  src/components/common/Table/Table.styled.ts
  src/components/common/Table/Table.test.tsx
  src/components/modal/SmsSendDetailInfoModalDialog/SmsSendDetailInfoModalDialog.component.tsx
  src/components/modal/SmsSendDetailInfoModalDialog/SmsSendDetailInfoModalDialog.stories.tsx
  src/components/modal/SmsSendDetailListModalDialog/SmsSendDetailListModalDialog.component.tsx
  src/components/modal/SmsSendDetailListModalDialog/SmsSendDetailListModalDialog.stories.tsx
  src/components/modal/index.ts
  src/pages/ApplicationDetailView/ApplicationDetailView.page.tsx
  src/pages/ApplicationList/ApplicationList.page.tsx
  src/pages/ApplicationList/ApplicationList.styled.ts
  src/store/login.ts
  src/store/modal.ts
  src/types/dto/adminMember.ts
  src/types/dto/application.ts
  src/utils/array.ts
Labels: deploy

#153 dayjs utc 변환시 Z 기준으로 시간이 변환되던 부분 수정
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx
  src/utils/date.ts
Labels: bug

#155 lodash-es 모듈을 설치하고 escape 되는 entitity를 unescape
  .pnp.cjs
  .yarn/cache/@types-lodash-es-npm-4.17.6-fd5abbdc74-9bd239dd52.zip
  .yarn/cache/@types-lodash-npm-4.14.180-37662c62d4-fc42ae3473.zip
  .yarn/cache/lodash-es-npm-4.17.21-b45832dfce-05cbffad6e.zip
  package.json
  src/components/ApplicationDetail/ApplicationQnAItem/ApplicationQnAItem.component.tsx
  yarn.lock
Labels: bug, feature

#156 QA 1차 대응 (v0.4.0) - dididy
  .pnp.cjs
  .yarn/cache/@types-lodash-es-npm-4.17.6-fd5abbdc74-9bd239dd52.zip
  .yarn/cache/@types-lodash-npm-4.14.180-37662c62d4-fc42ae3473.zip
  .yarn/cache/lodash-es-npm-4.17.21-b45832dfce-05cbffad6e.zip
  package.json
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx
  src/components/ApplicationDetail/ApplicationQnAItem/ApplicationQnAItem.component.tsx
  src/utils/date.ts
  yarn.lock
Labels: bug

#157 Qa Release/v0.4.0 - 2차
  .pnp.cjs
  .yarn/cache/@types-lodash-es-npm-4.17.6-fd5abbdc74-9bd239dd52.zip
  .yarn/cache/@types-lodash-npm-4.14.180-37662c62d4-fc42ae3473.zip
  .yarn/cache/lodash-es-npm-4.17.21-b45832dfce-05cbffad6e.zip
  package.json
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx
  src/components/ApplicationDetail/ApplicationQnAItem/ApplicationQnAItem.component.tsx
  src/utils/date.ts
  yarn.lock
Labels: deploy

#158 인적정보에도 entity unescape 로직을 추가
  src/pages/ApplicationDetailView/ApplicationDetailView.page.tsx
Labels: bug, feature

#154 Application list page에 SMS 일괄전송 모달 적용
  src/components/ApplicationDetail/MessageListPanel/MessageListPanel.component.tsx
  src/components/common/ModalViewer/ModalViewer.component.tsx
  src/components/common/ModalViewer/ModalViewer.stories.tsx
  src/components/common/Pagination/Pagination.component.tsx
  src/components/common/Pagination/Pagination.stories.tsx
  src/components/common/Pagination/PagingSizeSelector/PagingSizeSelector.tsx
  src/components/common/SmsSendModalDialog/SmsSendModalDialog.component.tsx
  src/components/common/SmsSendModalDialog/SmsSendModalDialog.stories.tsx
  src/components/common/SmsSendModalDialog/SmsSendModalDialog.styled.tsx
  src/components/common/Table/Table.component.tsx
  src/components/common/Table/Table.stories.tsx
  src/components/common/Table/Table.styled.ts
  src/components/modal/ChangeResultModalDialog/ChangeResultModalDialog.component.tsx
  src/components/modal/SmsSendDetailListModalDialog/SmsSendDetailListModalDialog.component.tsx
  src/components/modal/SmsSendDetailListModalDialog/SmsSendDetailListModalDialog.stories.tsx
  src/components/modal/SmsSendDetailListModalDialog/SmsSendDetailListModalDialog.styled.ts
  src/hooks/usePagination.test.ts
  src/hooks/usePagination.ts
  src/pages/ApplicationDetailView/ApplicationDetailView.page.tsx
  src/pages/ApplicationFormList/ApplicationFormList.page.tsx
  src/pages/ApplicationList/ApplicationList.page.tsx
  src/utils/string.ts
Labels: feature

#159 XLSX 파일로 export 하는 기능 추가
  .pnp.cjs
  .yarn/cache/adler-32-npm-1.3.0-5327bf60b0-91c3155198.zip
  .yarn/cache/cfb-npm-1.2.1-5312a38f7f-6d21a58c07.zip
  .yarn/cache/codepage-npm-1.15.0-bde3a4eb54-86bdfd8f8f.zip
  .yarn/cache/crc-32-npm-1.2.1-ac77b90365-b8942a4047.zip
  .yarn/cache/exit-on-epipe-npm-1.0.1-1aade96e24-e8ab494041.zip
  .yarn/cache/frac-npm-1.1.2-7e88efac4e-fbfbb28003.zip
  .yarn/cache/printj-npm-1.2.3-1beb2848dd-ba0bc4c087.zip
  .yarn/cache/printj-npm-1.3.1-5df08ba24a-3bb8976e02.zip
  .yarn/cache/ssf-npm-0.11.2-e6437eb624-6ecef6ae0a.zip
  .yarn/cache/wmf-npm-1.0.2-15d4e3e93c-d336acb2c7.zip
  .yarn/cache/word-npm-0.3.0-da20365d4a-f84e706188.zip
  .yarn/cache/xlsx-npm-0.18.5-f70d417ac6-c5774d3c6a.zip
  package.json
  src/hooks/index.ts
  src/hooks/useConvertToXlsx.ts
  src/pages/ApplicationList/ApplicationList.page.tsx
  src/types/dto/application.ts
  yarn.lock
Labels: feature

#161 인터뷰 결과 발표 이후에 합격 여부 변경을 못하도록 처리
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx
  src/components/modal/ChangeResultModalDialog/ChangeResultModalDialog.component.tsx
  src/utils/date.ts
Labels: bug, feature

#162 react-linkify 모듈로 답변에 링크 텍스트가 들어있으면 a 태그로 변환되도록 처리
  .pnp.cjs
  .yarn/cache/@types-react-linkify-npm-1.0.1-1b77eebe5c-e39435c6f2.zip
  .yarn/cache/linkify-it-npm-2.2.0-3eb4775d11-d198871d0b.zip
  .yarn/cache/react-linkify-npm-1.0.0-alpha-3cbf0408d2-abff36e1fd.zip
  .yarn/cache/tlds-npm-1.230.0-aaa9e0df1c-a1aa4e7a88.zip
  .yarn/cache/uc.micro-npm-1.0.6-36f3dc2fc4-6898bb5563.zip
  package.json
  src/components/ApplicationDetail/ApplicationQnAItem/ApplicationQnAItem.component.tsx
  src/components/ApplicationDetail/ApplicationQnAItem/ApplicationQnAItem.styled.ts
  yarn.lock
Labels: feature

#163 helper 롤 추가 및 dto, value 서버 기준으로 수정
  src/components/common/ApplicationStatusBadge/ApplicationStatusBadge.component.tsx
  src/components/common/ApplicationStatusBadge/ApplicationStatusBadge.stories.tsx
  src/components/common/Select/Select.stories.tsx
  src/components/common/UserProfile/UserProfile.component.tsx
  src/components/common/UserProfile/UserProfile.styled.ts
  src/styles/themes/badge.ts
  src/styles/themes/colors.ts
  src/styles/themes/userProfile.ts
  src/types/dto/adminMember.ts
  src/types/dto/application.ts
Labels: feature

#164 롤이 다를 경우 다른 팀 지원서 열람이 불가능하도록 처리
  src/App.tsx
  src/assets/svg/minsour-dori-248.svg
  src/assets/svg/minsour-sad-200.svg
  src/components/common/Table/Table.component.tsx
  src/components/common/Table/Table.testUtil.tsx
  src/constants/paths.ts
  src/pages/ApplicationDetailView/ApplicationDetailView.page.tsx
  src/pages/ApplicationList/ApplicationList.page.tsx
  src/pages/ApplicationList/ApplicationList.styled.ts
  src/pages/ErrorPage/ErrorPage.page.tsx
  src/pages/ErrorPage/ErrorPage.styled.ts
  src/pages/LoginPage/LoginPage.page.tsx
  src/pages/index.ts
Labels: feature

#166 # 제거, 지원서 리스트 버튼 disable 처리, 엑셀 export시 각 플랫폼 모든 인원을 내보내도록 처리
  src/pages/ApplicationList/ApplicationList.page.tsx
  src/pages/ApplicationList/ApplicationList.styled.ts
  src/store/modal.ts
Labels: bug

#160 QA 2차 대응 (v0.4.0) - dididy
  .pnp.cjs
  .yarn/cache/@types-react-linkify-npm-1.0.1-1b77eebe5c-e39435c6f2.zip
  .yarn/cache/adler-32-npm-1.3.0-5327bf60b0-91c3155198.zip
  .yarn/cache/cfb-npm-1.2.1-5312a38f7f-6d21a58c07.zip
  .yarn/cache/codepage-npm-1.15.0-bde3a4eb54-86bdfd8f8f.zip
  .yarn/cache/crc-32-npm-1.2.1-ac77b90365-b8942a4047.zip
  .yarn/cache/exit-on-epipe-npm-1.0.1-1aade96e24-e8ab494041.zip
  .yarn/cache/frac-npm-1.1.2-7e88efac4e-fbfbb28003.zip
  .yarn/cache/linkify-it-npm-2.2.0-3eb4775d11-d198871d0b.zip
  .yarn/cache/printj-npm-1.2.3-1beb2848dd-ba0bc4c087.zip
  .yarn/cache/printj-npm-1.3.1-5df08ba24a-3bb8976e02.zip
  .yarn/cache/react-linkify-npm-1.0.0-alpha-3cbf0408d2-abff36e1fd.zip
  .yarn/cache/ssf-npm-0.11.2-e6437eb624-6ecef6ae0a.zip
  .yarn/cache/tlds-npm-1.230.0-aaa9e0df1c-a1aa4e7a88.zip
  .yarn/cache/uc.micro-npm-1.0.6-36f3dc2fc4-6898bb5563.zip
  .yarn/cache/wmf-npm-1.0.2-15d4e3e93c-d336acb2c7.zip
  .yarn/cache/word-npm-0.3.0-da20365d4a-f84e706188.zip
  .yarn/cache/xlsx-npm-0.18.5-f70d417ac6-c5774d3c6a.zip
  package.json
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx
  src/components/ApplicationDetail/ApplicationQnAItem/ApplicationQnAItem.component.tsx
  src/components/ApplicationDetail/ApplicationQnAItem/ApplicationQnAItem.styled.ts
  src/components/modal/ChangeResultModalDialog/ChangeResultModalDialog.component.tsx
  src/hooks/index.ts
  src/hooks/useConvertToXlsx.ts
  src/pages/ApplicationDetailView/ApplicationDetailView.page.tsx
  src/pages/ApplicationList/ApplicationList.page.tsx
  src/pages/ApplicationList/ApplicationList.styled.ts
  src/store/modal.ts
  src/types/dto/application.ts
  src/utils/date.ts
  yarn.lock
Labels: deploy

#168 Feature/sms list page
  src/App.tsx
  src/api/sms.ts
  src/components/ApplicationDetail/MessageListPanel/MessageListPanel.component.tsx
  src/components/common/ModalViewer/ModalViewer.component.tsx
  src/components/common/Table/Table.component.tsx
  src/components/modal/SmsSendDetailInfoModalDialog/SmsSendDetailInfoModalDialog.component.tsx
  src/components/modal/SmsSendDetailInfoModalDialog/SmsSendDetailInfoModalDialog.stories.tsx
  src/components/modal/SmsSendDetailInfoModalDialog/SmsSendDetailInfoModalDialog.styled.ts
  src/pages/ApplicationFormList/ApplicationFormList.page.tsx
  src/pages/ApplicationList/ApplicationList.page.tsx
  src/pages/SmsSendingList/SmsSendingList.page.tsx
  src/pages/SmsSendingList/SmsSendingList.styled.ts
  src/pages/index.ts
  src/store/index.ts
  src/store/modal.ts
  src/store/sms.ts
  src/types/dto/index.ts
  src/types/dto/sms.ts
  src/utils/index.ts
  src/utils/object.ts
Labels: feature

#169 QA 3차 대응 (v0.4.0) - dididy
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx
  src/components/common/SmsSendModalDialog/SmsSendModalDialog.component.tsx
  src/components/common/Table/Table.component.tsx
  src/components/modal/SmsSendDetailInfoModalDialog/SmsSendDetailInfoModalDialog.component.tsx
  src/components/modal/SmsSendDetailListModalDialog/SmsSendDetailListModalDialog.component.tsx
  src/pages/ApplicationList/ApplicationList.page.tsx
Labels: bug

#171 Qa Release/v0.4.0 - 3차
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx
  src/components/common/SmsSendModalDialog/SmsSendModalDialog.component.tsx
  src/components/common/Table/Table.component.tsx
  src/components/modal/SmsSendDetailInfoModalDialog/SmsSendDetailInfoModalDialog.component.tsx
  src/components/modal/SmsSendDetailListModalDialog/SmsSendDetailListModalDialog.component.tsx
  src/pages/ApplicationList/ApplicationList.page.tsx
Labels: deploy

#175 QA 4차 대응 (v0.4.0) - dididy
  src/store/modal.ts
Labels: bug

#177 QA 5차 대응 (v0.4.0) - minsour
  src/components/common/SearchOptionBar/SearchOptionBar.component.tsx
  src/hooks/usePagination.ts
  src/pages/ApplicationFormList/ApplicationFormList.page.tsx
  src/pages/ApplicationList/ApplicationList.page.tsx
  src/pages/SmsSendingList/SmsSendingList.page.tsx
Labels: bug

#179 QA 6차 대응 (v0.4.0) - dididy
  src/components/common/Table/Table.component.tsx
  src/pages/ApplicationList/ApplicationList.page.tsx
  src/pages/ApplicationList/ApplicationList.styled.ts
Labels: bug

#180 Main Release/v0.4.0
  src/components/common/Table/Table.component.tsx
  src/pages/ApplicationList/ApplicationList.page.tsx
  src/pages/ApplicationList/ApplicationList.styled.ts
Labels: deploy

#182 QA 7차 대응 (v0.4.0) - dididy
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx
  src/components/common/Toast/Toast.styled.ts
Labels: bug

#183 Main Release/v0.4.0
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx
  src/components/common/Toast/Toast.styled.ts
  src/utils/date.ts
Labels: deploy

#186 QA 9차 대응 (v0.4.0) - dididy
  src/pages/ApplicationList/ApplicationList.page.tsx
  src/utils/date.ts
Labels: bug

#188 QA 10차 대응 (v0.4.0) - dididy
  src/components/modal/ChangeResultModalDialog/ChangeResultModalDialog.component.tsx
  src/pages/ApplicationList/ApplicationList.page.tsx
Labels: bug

#191 QA 11차 대응 (v0.4.0) - dididy
  .pnp.cjs
  .yarn/cache/@types-react-linkify-npm-1.0.1-1b77eebe5c-e39435c6f2.zip
  .yarn/cache/linkify-it-npm-2.2.0-3eb4775d11-d198871d0b.zip
  .yarn/cache/react-linkify-npm-1.0.0-alpha-3cbf0408d2-abff36e1fd.zip
  .yarn/cache/tlds-npm-1.230.0-aaa9e0df1c-a1aa4e7a88.zip
  .yarn/cache/uc.micro-npm-1.0.6-36f3dc2fc4-6898bb5563.zip
  package.json
  src/components/ApplicationDetail/ApplicationQnAItem/ApplicationQnAItem.component.tsx
  src/pages/ApplicationDetailView/ApplicationDetailView.page.tsx
  src/utils/index.ts
  src/utils/linkify.ts
  yarn.lock
Labels: bug

#193 QA 13차 대응 (v0.4.0) - dididy
  src/components/ApplicationDetail/ApplicationQnAItem/ApplicationQnAItem.styled.ts
  src/components/ApplicationDetail/MessageListPanel/MessageListPanel.component.tsx
  src/components/ApplicationDetail/MessageListPanel/MessageListPanel.stories.tsx
  src/components/modal/ChangeResultModalDialog/ChangeResultModalDialog.component.tsx
  src/components/modal/SmsSendDetailInfoModalDialog/SmsSendDetailInfoModalDialog.stories.tsx
  src/types/dto/sms.ts
Labels: bug

#194 QA 14차 대응 (v0.4.0) - dididy
  public/index.html
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx
  src/components/ApplicationDetail/ApplicationQnAItem/ApplicationQnAItem.component.tsx
  src/components/ApplicationForm/ApplicationFormPreview/ApplicationFormPreview.component.tsx
  src/hooks/index.ts
  src/hooks/useConvertTextToLink.tsx
  src/utils/index.ts
  src/utils/linkify.ts
Labels: bug

#195 Main Release/v0.4.0
  public/index.html
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx
  src/components/ApplicationDetail/ApplicationQnAItem/ApplicationQnAItem.component.tsx
  src/components/ApplicationForm/ApplicationFormPreview/ApplicationFormPreview.component.tsx
  src/hooks/index.ts
  src/hooks/useConvertTextToLink.tsx
  src/utils/index.ts
  src/utils/linkify.ts
Labels: deploy
