Repository mash-up-kr/mash-up-admin-fe, pull requests merged in 2022-02, with the labels that each got.

#22 tsconfig target es5로 수정 및 recruit과 동기화
  .gitignore
  package.json
  tsconfig.json
Labels: env

#23 Input 컴포넌트 추가
  .eslintrc.json
  .github/workflows/ci.yaml
  .storybook/main.js
  .storybook/preview.js
  @types/custom-types/emotion.d.ts
  src/components/common/Input/Input.component.tsx
  src/components/common/Input/Input.stories.tsx
  src/components/common/Input/Input.styled.ts
  src/components/common/index.ts
  src/components/index.ts
  src/styles/themes/fonts.ts
  src/styles/themes/index.ts
  src/styles/themes/input.ts
  src/styles/themes/theme.ts
  src/types/helper.ts
  src/types/index.ts
  src/utils/errors.ts
Labels: feature

#27 ModalWrapper 컴포넌트 추가
  src/assets/svg/close-icon.svg
  src/components/common/ModalWrapper/ModalWrapper.component.tsx
  src/components/common/ModalWrapper/ModalWrapper.stories.tsx
  src/components/common/ModalWrapper/ModalWrapper.styled.ts
  src/components/common/index.ts
  src/styles/themes/fonts.ts
Labels: feature

#28 ToggleButton 컴포넌트 추가
  src/components/common/ToggleButton/ToggleButton.component.tsx
  src/components/common/ToggleButton/ToggleButton.stories.tsx
  src/components/common/ToggleButton/ToggleButton.styled.ts
  src/components/common/index.ts
Labels: feature

#29 Checkbox 컴포넌트 추가
  src/assets/svg/checkbox-checked.svg
  src/components/common/Checkbox/Checkbox.component.tsx
  src/components/common/Checkbox/Checkbox.stories.tsx
  src/components/common/Checkbox/Checkbox.styled.ts
  src/components/common/index.ts
Labels: feature

#32 BackButton 컴포넌트 추가
  src/assets/svg/chevron-left.svg
  src/components/common/BackButton/BackButton.component.tsx
  src/components/common/BackButton/BackButton.stories.tsx
  src/components/common/BackButton/BackButton.styled.ts
  src/components/common/index.ts
Labels: feature

#34 Navigation 컴포넌트 추가
  .storybook/preview.js
  @types/custom-types/emotion.d.ts
  src/components/common/Navigation/Navigation.component.tsx
  src/components/common/Navigation/Navigation.stories.tsx
  src/components/common/Navigation/Navigation.styled.ts
  src/components/common/index.ts
  src/styles/resetCss.ts
  src/styles/themes/fonts.ts
  src/styles/themes/index.ts
  src/styles/themes/navigation.ts
  src/styles/themes/theme.ts
Labels: feature

#33 VisuallyHidden 컴포넌트 추가
  @types/custom-types/emotion.d.ts
  src/components/common/Checkbox/Checkbox.component.tsx
  src/components/common/Checkbox/Checkbox.styled.ts
  src/components/common/RadioButton/RadioButton.component.tsx
  src/components/common/RadioButton/RadioButton.styled.ts
  src/components/common/ToggleButton/ToggleButton.component.tsx
  src/components/common/ToggleButton/ToggleButton.styled.ts
  src/styles/themes/a11y.ts
  src/styles/themes/index.ts
  src/styles/themes/theme.ts
Labels: feature

#40 svg 파일 -width 형태로 네이밍 변경 및 theme.button 에 hover, disabled 스타일 추가
  src/assets/svg/checkbox-active-12.svg
  src/assets/svg/chevron-left-16.svg
  src/assets/svg/open-external-20.svg
  src/assets/svg/popup-close-44.svg
  src/components/common/BackButton/BackButton.component.tsx
  src/components/common/Button/Button.stories.tsx
  src/components/common/Checkbox/Checkbox.component.tsx
  src/components/common/ModalWrapper/ModalWrapper.component.tsx
  src/styles/themes/button.ts
  src/styles/themes/colors.ts
Labels: feature

#38 UserProfile 컴포넌트 추가
  @types/custom-types/emotion.d.ts
  src/components/common/UserProfile/UserProfile.component.tsx
  src/components/common/UserProfile/UserProfile.stories.tsx
  src/components/common/UserProfile/UserProfile.styled.ts
  src/styles/themes/colors.ts
  src/styles/themes/index.ts
  src/styles/themes/theme.ts
  src/styles/themes/userProfile.ts
Labels: feature

#41 Header, Layout 컴포넌트 추가
  src/App.tsx
  src/assets/svg/logo-admin-272.svg
  src/components/common/Header/Header.component.tsx
  src/components/common/Header/Header.stories.tsx
  src/components/common/Header/Header.styled.ts
  src/components/common/Layout/Layout.component.tsx
  src/components/common/Layout/Layout.styled.ts
  src/components/common/Link/Link.component.tsx
  src/components/common/Navigation/Navigation.styled.ts
  src/components/common/index.ts
  src/constants/index.ts
  src/constants/ui.ts
Labels: feature

#36 Pagination 컴포넌트 추가
  .eslintignore
  .eslintrc.json
  .pnp.cjs
  .storybook/preview.js
  .stylelintignore
  .yarn/cache/@testing-library-react-hooks-npm-7.0.2-da146b13d2-27c6169b5c.zip
  .yarn/cache/@testing-library-user-event-npm-13.5.0-1ff89b703a-16319de685.zip
  .yarn/cache/@types-react-npm-17.0.39-b4ac1f7bfe-bf04d3c289.zip
  .yarn/cache/@types-react-test-renderer-npm-17.0.1-9a42d8bb68-ecaae8df36.zip
  .yarn/cache/@types-testing-library__dom-npm-7.5.0-ed4d624eaf-fe38a1f42c.zip
  .yarn/cache/@types-testing-library__react-npm-10.2.0-decb94f1b1-85f4db1aee.zip
  .yarn/cache/@types-testing-library__user-event-npm-4.2.0-2c78914728-31ad1437c9.zip
  .yarn/cache/@typescript-eslint-scope-manager-npm-5.10.2-bbe440721d-22c8ac9047.zip
  .yarn/cache/@typescript-eslint-types-npm-5.10.2-f79ab708e6-fa44dbd31d.zip
  .yarn/cache/@typescript-eslint-typescript-estree-npm-5.10.2-f127d534b0-2fdad14485.zip
  .yarn/cache/@typescript-eslint-utils-npm-5.10.2-af028682a6-d0dde3066f.zip
  .yarn/cache/@typescript-eslint-visitor-keys-npm-5.10.2-b2ee462752-f80caa1f0d.zip
  .yarn/cache/eslint-config-airbnb-typescript-npm-16.1.0-3c8d73d72a-65bb6763ab.zip
  .yarn/cache/eslint-plugin-jest-npm-26.1.0-5d0144d71e-5d79609264.zip
  .yarn/cache/eslint-plugin-testing-library-npm-5.0.5-6ee043fdb9-423b5c27ce.zip
  .yarn/cache/react-error-boundary-npm-3.1.4-2310dba89e-f36270a5d7.zip
  package.json
  src/App.test.tsx
  src/assets/svg/chevron-left-24.svg
  src/assets/svg/chevron-right-24.svg
  src/assets/svg/chevrondouble-left-24.svg
  src/assets/svg/chevrondouble-right-24.svg
  src/components/common/Pagination/PageButtonList/PageButtonList.component.tsx
  src/components/common/Pagination/PageButtonList/PageButtonList.styled.ts
  src/components/common/Pagination/PageButtonList/PageButtonList.test.tsx
  src/components/common/Pagination/Pagination.component.tsx
  src/components/common/Pagination/Pagination.stories.tsx
  src/components/common/Pagination/Pagination.styled.ts
  src/components/common/Pagination/PagingSizeSelector/PagingSizeSelector.tsx
  src/components/common/index.ts
  src/hooks/index.ts
  src/hooks/useMount.test.ts
  src/hooks/useMount.ts
  src/hooks/usePagination.test.ts
  src/hooks/usePagination.ts
  tsconfig.json
  yarn.lock
Labels: feature

#37 DatePicker 컴포넌트 추가
  .pnp.cjs
  .yarn/cache/dayjs-npm-1.10.7-34318a8e39-a0a4ca95ab.zip
  package.json
  src/components/common/DatePicker/DatePicker.component.tsx
  src/components/common/DatePicker/DatePicker.stories.tsx
  src/components/common/DatePicker/DatePicker.styled.ts
  src/components/common/index.ts
  src/styles/themes/fonts.ts
  yarn.lock
Labels: feature

#46 rangeArray 유틸 함수 추가
  src/components/common/DatePicker/DatePicker.component.tsx
  src/components/common/Pagination/PageButtonList/PageButtonList.component.tsx
  src/utils/array.test.ts
  src/utils/array.ts
  src/utils/index.ts
Labels: feature

#49 pathname에 따라 배경 색을 white, gray10 으로 각각 토글되도록 처리
  src/components/common/Layout/Layout.component.tsx
  src/components/common/Layout/Layout.styled.ts
Labels: feature

#45 Select 컴포넌트 추가
  @types/custom-types/emotion.d.ts
  src/assets/svg/chevron-down-16.svg
  src/components/common/Select/Select.component.tsx
  src/components/common/Select/Select.stories.tsx
  src/components/common/Select/Select.styled.ts
  src/components/common/index.ts
  src/hooks/index.ts
  src/hooks/useOnClickOutSide.ts
  src/hooks/useToggleState.ts
  src/styles/themes/index.ts
  src/styles/themes/navigation.ts
  src/styles/themes/select.ts
  src/styles/themes/theme.ts
Labels: feature

#43 ModalViewer, AlertModalDialog 컴포넌트 추가
  @types/custom-types/emotion.d.ts
  package.json
  src/App.test.tsx
  src/App.tsx
  src/atoms.ts
  src/components/Count.tsx
  src/components/common/AlertModalDialog/AlertModalDialog.component.tsx
  src/components/common/AlertModalDialog/AlertModalDialog.stories.tsx
  src/components/common/AlertModalDialog/AlertModalDialog.styled.ts
  src/components/common/Button/Button.component.tsx
  src/components/common/Checkbox/Checkbox.stories.tsx
  src/components/common/ModalViewer/ModalViewer.component.tsx
  src/components/common/ModalViewer/ModalViewer.stories.tsx
  src/components/common/ModalWrapper/ModalWrapper.component.tsx
  src/components/common/ModalWrapper/ModalWrapper.stories.tsx
  src/components/common/ModalWrapper/ModalWrapper.styled.ts
  src/components/common/RadioButton/RadioButton.stories.tsx
  src/components/common/ToggleButton/ToggleButton.stories.tsx
  src/components/common/index.ts
  src/store/index.ts
  src/store/modal.ts
  src/styles/resetCss.ts
  src/styles/themes/fonts.ts
  src/styles/themes/index.ts
  src/styles/themes/theme.ts
  src/styles/themes/zIndex.ts
Labels: feature

#44 Label 컴포넌트 추가 => ApplicationStatusBadge 로 이름 변경
  @types/custom-types/emotion.d.ts
  src/components/common/ApplicationStatusBadge/ApplicationStatusBadge.component.tsx
  src/components/common/ApplicationStatusBadge/ApplicationStatusBadge.stories.tsx
  src/components/common/ApplicationStatusBadge/ApplicationStatusBadge.styled.ts
  src/components/common/index.ts
  src/styles/themes/badge.ts
  src/styles/themes/colors.ts
  src/styles/themes/index.ts
  src/styles/themes/theme.ts
Labels: feature

#50 지원설문지 작성 페이지 UI 추가
  public/index.html
  src/App.tsx
  src/assets/svg/plus-20.svg
  src/assets/svg/preview-20.svg
  src/components/ApplicationForm/ApplicationFormItem/ApplicationFormItem.component.tsx
  src/components/ApplicationForm/CreateApplicationFormAside/CreateApplicationFormAside.component.tsx
  src/components/ApplicationForm/CreateApplicationFormAside/CreateApplicationFormAside.stories.tsx
  src/components/ApplicationForm/CreateApplicationFormAside/CreateApplicationFormAside.styled.ts
  src/components/ApplicationForm/index.ts
  src/components/common/Header/Header.component.tsx
  src/components/common/Navigation/Navigation.component.tsx
  src/components/common/Navigation/Navigation.stories.tsx
  src/components/common/UserProfile/UserProfile.component.tsx
  src/components/common/UserProfile/UserProfile.styled.ts
  src/constants/index.ts
  src/constants/paths.ts
  src/pages/ApplicationFormControl/ApplicationFormControl.page.tsx
  src/pages/ApplicationFormControl/ApplicationFormControl.styled.ts
  src/pages/index.ts
  src/utils/uuid.ts
Labels: feature

#54 RequiredAuth 컴포넌트로 로그인 여부에 따라 특정 경로로 리다이렉트 되도록 처리
  .pnp.cjs
  .yarn/cache/recoil-npm-0.5.2-d5de0b4507-1daf09f969.zip
  .yarn/cache/recoil-npm-0.6.1-12c4d62952-823c098e30.zip
  package.json
  src/App.tsx
  src/api/core.ts
  src/api/index.ts
  src/api/login.ts
  src/components/common/Header/Header.component.tsx
  src/components/common/UserProfile/UserProfile.component.tsx
  src/pages/LoginPage/LoginPage.page.tsx
  src/store/login.ts
  src/store/recoil.ts
  src/types/dto/AdminMember.ts
  src/types/dto/base.ts
  src/types/dto/index.ts
  src/utils/errors.ts
  yarn.lock
Labels: feature

#53 react-hook-form fields들 추가
  .pnp.cjs
  .yarn/cache/react-hook-form-npm-7.27.0-edb8aa4983-643c643e6d.zip
  package.json
  src/components/ApplicationForm/ApplicationFormItem/ApplicationFormItem.component.tsx
  src/components/common/Input/Input.component.tsx
  src/components/common/Select/Select.component.tsx
  src/components/common/Select/Select.stories.tsx
  src/components/common/Select/Select.styled.ts
  src/components/common/ToggleButton/ToggleButton.component.tsx
  src/components/fields/InputField/InputField.component.tsx
  src/components/fields/SelectField/SelectField.component.tsx
  src/components/fields/ToggleButtonField/ToggleButtonField.component.tsx
  src/components/fields/index.ts
  src/components/index.ts
  yarn.lock
Labels: feature

#47 url fragment 에 따라 켜져있는 모달이 유지되도록 처리
  .pnp.cjs
  .yarn/cache/recoil-persist-npm-4.0.0-25c546b380-95ac8d6bab.zip
  package.json
  src/App.tsx
  src/components/common/AlertModalDialog/AlertModalDialog.component.tsx
  src/components/common/ModalViewer/ModalViewer.component.tsx
  src/components/common/ModalViewer/ModalViewer.stories.tsx
  src/store/modal.ts
  yarn.lock
Labels: feature

#59 Login에서 TODO 로 남겨뒀던 부분 수정
  .pnp.cjs
  package.json
  src/App.tsx
  src/api/core.ts
  src/pages/LoginPage/LoginPage.page.tsx
  src/styles/themes/userProfile.ts
  src/types/dto/adminMember.ts
  src/types/dto/index.ts
Labels: bug

#55 지원서 양식 추가 react-hook-form 연동
  src/components/ApplicationForm/ApplicationFormItem/ApplicationFormItem.component.tsx
  src/components/ApplicationForm/ApplicationFormItem/ApplicationFormItem.styled.ts
  src/components/ApplicationForm/CreateApplicationFormAside/CreateApplicationFormAside.component.tsx
  src/components/common/Input/Input.component.tsx
  src/components/common/Input/Input.styled.ts
  src/components/common/Select/Select.component.tsx
  src/components/common/Textarea/Textarea.component.tsx
  src/components/common/ToggleButton/ToggleButton.component.tsx
  src/pages/ApplicationFormControl/ApplicationFormControl.page.tsx
  src/pages/ApplicationFormControl/ApplicationFormControl.styled.ts
  src/styles/themes/colors.ts
  src/types/dto/applicationForm.ts
  src/types/dto/index.ts
  tsconfig.json
Labels: feature

#60 API core 오류 수정
  src/api/core.ts
Labels: bug

#63 Env: Vercel과 호환성을 위해 node.js version 다운그레이드
  .github/workflows/ci.yaml
  .nvmrc
  package.json
Labels: env

#75 vercel 빌드관련 문제 및 subrouter 새로고침 이슈 해결
  .env.example
  package.json
  src/styles/resetCss.ts
  vercel.json
Labels: bug

#58 지원서 양식 추가 api 연동
  src/api/applicationForm.ts
  src/api/index.ts
  src/components/ApplicationForm/ApplicationFormItem/ApplicationFormItem.component.tsx
  src/pages/ApplicationFormControl/ApplicationFormControl.page.tsx
  src/types/dto/applicationForm.ts
Labels: feature

#62 지원서 설문지 상세페이지 UI 추가
  src/App.tsx
  src/components/ApplicationForm/ApplicationFormSection/ApplicationFormSection.component.tsx
  src/components/ApplicationForm/ApplicationFormSection/ApplicationFormSection.styled.ts
  src/components/ApplicationForm/index.ts
  src/components/common/Input/Input.component.tsx
  src/components/common/Input/Input.styled.ts
  src/components/common/Textarea/Textarea.component.tsx
  src/components/common/Textarea/Textarea.styled.ts
  src/pages/ApplicationFormControl/ApplicationFormControl.page.tsx
  src/pages/ApplicationFormControl/ApplicationFormControl.styled.ts
  src/pages/ApplicationFormDetail/ApplicationFormDetail.page.tsx
  src/pages/ApplicationFormDetail/ApplicationFormDetail.styled.ts
  src/pages/index.ts
Labels: feature

#77 지원서 설문지 상세 api 연동
  src/App.tsx
  src/api/applicationForm.ts
  src/components/ApplicationForm/ApplicationFormAside/ApplicationFormAside.component.tsx
  src/components/ApplicationForm/ApplicationFormAside/ApplicationFormAside.stories.tsx
  src/components/ApplicationForm/ApplicationFormAside/ApplicationFormAside.styled.ts
  src/components/ApplicationForm/CreateApplicationFormAside/CreateApplicationFormAside.component.tsx
  src/components/ApplicationForm/CreateApplicationFormAside/CreateApplicationFormAside.stories.tsx
  src/components/ApplicationForm/index.ts
  src/components/common/UserProfile/UserProfile.component.tsx
  src/pages/ApplicationFormControl/ApplicationFormControl.page.tsx
  src/pages/ApplicationFormDetail/ApplicationFormDetail.page.tsx
  src/pages/ApplicationFormDetail/ApplicationFormDetail.styled.ts
  src/store/applicationForm.ts
  src/store/login.ts
  src/types/dto/adminMember.ts
  src/types/dto/applicationForm.ts
  src/types/helper.ts
  src/utils/date.ts
  src/utils/index.ts
Labels: feature

#78 지원설문지 팀 선택할 수 있게 추가
  src/App.tsx
  src/api/index.ts
  src/api/team.ts
  src/components/ApplicationForm/ApplicationFormItem/ApplicationFormItem.component.tsx
  src/components/common/Select/Select.component.tsx
  src/components/common/ToggleButton/ToggleButton.component.tsx
  src/pages/ApplicationFormControl/ApplicationFormControl.page.tsx
  src/pages/ApplicationFormControl/ApplicationFormControl.styled.ts
  src/store/index.ts
  src/store/team.ts
  src/styles/resetCss.ts
  src/types/dto/applicationForm.ts
  src/types/dto/index.ts
  src/types/dto/team.ts
Labels: bug, feature

#80 지원서 설문지 수정기능 추가
  src/App.tsx
  src/api/applicationForm.ts
  src/components/ApplicationForm/ApplicationFormAside/ApplicationFormAside.component.tsx
  src/components/ApplicationForm/ApplicationFormItem/ApplicationFormItem.component.tsx
  src/components/ApplicationForm/ApplicationFormTemplate/ApplicationFormTemplate.component.tsx
  src/components/ApplicationForm/ApplicationFormTemplate/ApplicationFormTemplate.style.ts
  src/components/common/ToggleButton/ToggleButton.component.tsx
  src/pages/CreateApplicationForm/CreateApplicationForm.page.tsx
  src/pages/CreateApplicationForm/CreateApplicationForm.styled.ts
  src/pages/UpdateApplicationForm/UpdateApplicationForm.page.tsx
  src/pages/UpdateApplicationForm/UpdateApplicationForm.styled.ts
  src/pages/index.ts
  src/store/index.ts
  src/types/dto/applicationForm.ts
Labels: bug, enhancement, feature

#81 지원서 설문지 삭제 기능 추가
  src/App.tsx
  src/api/applicationForm.ts
  src/components/ApplicationForm/ApplicationFormAside/ApplicationFormAside.component.tsx
  src/pages/ApplicationFormDetail/ApplicationFormDetail.page.tsx
Labels: feature

#83 지원설문지 미리보기 추가
  src/components/ApplicationForm/ApplicationFormAside/ApplicationFormAside.component.tsx
  src/components/ApplicationForm/ApplicationFormPreview/ApplicationFormPreview.component.tsx
  src/components/ApplicationForm/ApplicationFormPreview/ApplicationFormPreview.styled.ts
  src/components/common/Checkbox/Checkbox.component.tsx
  src/components/common/ModalWrapper/ModalWrapper.component.tsx
  src/components/common/ModalWrapper/ModalWrapper.styled.ts
  src/pages/CreateApplicationForm/CreateApplicationForm.page.tsx
Labels: bug, feature

#84 Table 컴포넌트 추가
  .eslintrc.json
  .stylelintrc
  src/components/common/Loading/Loading.component.tsx
  src/components/common/Loading/Loading.styled.ts
  src/components/common/Pagination/PageButtonList/PageButtonList.test.tsx
  src/components/common/Pagination/PageButtonList/PageButtonList.testUtil.tsx
  src/components/common/Table/Table.component.tsx
  src/components/common/Table/Table.styled.ts
  src/components/common/Table/Table.test.tsx
  src/components/common/Table/Table.testUtil.tsx
  src/components/common/index.ts
  src/types/dto/application.ts
  src/types/dto/index.ts
  src/types/helper.ts
  src/utils/index.ts
  src/utils/object.test.ts
  src/utils/object.ts
  src/utils/type.ts
Labels: feature

#82 로그인 풀리는 이슈 해결, 로그인 input을 react-hook-form으로 리팩토링
  src/App.tsx
  src/pages/LoginPage/LoginPage.page.tsx
  src/store/login.ts
Labels: bug

#85 PagingSizeSelector 컴포넌트에 Select 컴포넌트 적용
  src/components/common/Pagination/PageButtonList/PageButtonList.styled.ts
  src/components/common/Pagination/Pagination.component.tsx
  src/components/common/Pagination/Pagination.stories.tsx
  src/components/common/Pagination/Pagination.styled.ts
  src/components/common/Pagination/PagingSizeSelector/PagingSizeSelector.tsx
  src/components/common/Select/Select.component.tsx
  src/hooks/usePagination.ts
Labels: feature

#89 지원서 설문지 상세페이지 가지지 않는 버그 수정
  src/App.tsx
  src/pages/ApplicationFormDetail/ApplicationFormDetail.page.tsx
Labels: bug

#90 Toast 컴포넌트 추가
  @types/custom-types/emotion.d.ts
  src/App.tsx
  src/assets/svg/close-green-32.svg
  src/assets/svg/close-red-32.svg
  src/assets/svg/error-24.svg
  src/assets/svg/success-24.svg
  src/components/common/Toast/Toast.component.tsx
  src/components/common/Toast/Toast.stories.tsx
  src/components/common/Toast/Toast.styled.ts
  src/components/common/index.ts
  src/hooks/index.ts
  src/hooks/useToast.ts
  src/store/index.ts
  src/store/toast.ts
  src/styles/themes/colors.ts
  src/styles/themes/index.ts
  src/styles/themes/theme.ts
  src/styles/themes/toast.ts
Labels: feature

#91 AlertModalDialog에 핸들러를 넣고 새로고침시 유지 안되도록 처리
  src/components/common/AlertModalDialog/AlertModalDialog.component.tsx
  src/components/common/AlertModalDialog/AlertModalDialog.stories.tsx
  src/components/common/ModalViewer/ModalViewer.component.tsx
  src/components/common/ModalViewer/ModalViewer.stories.tsx
  src/store/modal.ts
Labels: bug, feature

#88 기존 작업범위 마무리 및 스크럼 후 TODO 반영
  src/App.tsx
  src/api/application.ts
  src/api/core.ts
  src/api/index.ts
  src/api/sms.ts
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.stories.tsx
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.styled.ts
  src/components/ApplicationDetail/ApplicationQnAItem/ApplicationQnAItem.component.tsx
  src/components/ApplicationDetail/ApplicationQnAItem/ApplicationQnAItem.stories.tsx
  src/components/ApplicationDetail/ApplicationQnAItem/ApplicationQnAItem.styled.ts
  src/components/ApplicationDetail/MessageListPanel/MessageListPanel.component.tsx
  src/components/ApplicationDetail/MessageListPanel/MessageListPanel.stories.tsx
  src/components/ApplicationDetail/MessageListPanel/MessageListPanel.styled.tsx
  src/components/ApplicationDetail/SmsSendModalDialog/SmsSendModalDialog.component.tsx
  src/components/ApplicationDetail/SmsSendModalDialog/SmsSendModalDialog.stories.tsx
  src/components/ApplicationDetail/SmsSendModalDialog/SmsSendModalDialog.styled.tsx
  src/components/ApplicationDetail/TitleWithContent/TitleWithContent.component.tsx
  src/components/ApplicationDetail/TitleWithContent/TitleWithContent.stories.tsx
  src/components/ApplicationDetail/TitleWithContent/TitleWithContent.styled.ts
  src/components/ApplicationDetail/index.ts
  src/components/common/ApplicationStatusBadge/ApplicationStatusBadge.component.tsx
  src/components/common/DatePicker/DatePicker.styled.ts
  src/components/common/ModalViewer/ModalViewer.component.tsx
  src/components/common/ModalViewer/ModalViewer.stories.tsx
  src/components/common/Select/Select.component.tsx
  src/components/common/Select/Select.stories.tsx
  src/components/common/Select/Select.styled.ts
  src/components/common/Textarea/Textarea.component.tsx
  src/components/index.ts
  src/pages/ApplicationDetailView/ApplicationDetailView.page.tsx
  src/pages/ApplicationDetailView/ApplicationDetailView.styled.ts
  src/pages/LoginPage/LoginPage.page.tsx
  src/pages/index.ts
  src/store/application.ts
  src/store/index.ts
  src/store/modal.ts
  src/styles/themes/badge.ts
  src/styles/themes/fonts.ts
  src/styles/themes/zIndex.ts
  src/types/dto/applicationById.ts
  src/types/dto/index.ts
  src/types/dto/sms.ts
  src/utils/date.ts
Labels: bug, feature

#93 MASHUP_SUBLEADER 처럼 SUBLEADER에 공백을 제거한다
  src/components/common/UserProfile/UserProfile.component.tsx
  src/styles/themes/userProfile.ts
Labels: bug

#98 지원서 설문지 내역 페이지 추가
  src/App.tsx
  src/api/applicationForm.ts
  src/components/ApplicationForm/ApplicationFormPreview/ApplicationFormPreview.component.tsx
  src/components/common/Button/Button.component.tsx
  src/components/common/Header/Header.styled.ts
  src/components/common/SearchOptionBar/SearchOptionBar.component.tsx
  src/components/common/SearchOptionBar/SearchOptionBar.styled.ts
  src/components/common/Table/Table.styled.ts
  src/components/common/TeamNavigationTabs/TeamNavigationTabs.component.tsx
  src/components/common/TeamNavigationTabs/TeamNavigationTabs.styled.ts
  src/components/common/index.ts
  src/pages/ApplicationFormList/ApplicationFormList.page.tsx
  src/pages/ApplicationFormList/ApplicationFormList.styled.ts
  src/pages/index.ts
  src/store/applicationForm.ts
  src/store/team.ts
  src/styles/themes/button.ts
  src/types/dto/applicationForm.ts
Labels: feature

#94 지원서 설문지 생성 수정 삭제 전 확인 모달띄우도록 추가
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx
  src/components/ApplicationForm/ApplicationFormItem/ApplicationFormItem.component.tsx
  src/components/common/ModalWrapper/ModalWrapper.component.tsx
  src/components/common/Pagination/PagingSizeSelector/PagingSizeSelector.tsx
  src/components/common/Select/Select.component.tsx
  src/pages/ApplicationFormDetail/ApplicationFormDetail.page.tsx
  src/pages/CreateApplicationForm/CreateApplicationForm.page.tsx
  src/pages/UpdateApplicationForm/UpdateApplicationForm.page.tsx
Labels: feature

#95 모달 관련 리팩토링
  src/components/ApplicationDetail/ApplicationPanel/ApplicationPanel.component.tsx
  src/components/ApplicationDetail/MessageListPanel/MessageListPanel.component.tsx
  src/components/ApplicationDetail/SmsSendModalDialog/SmsSendModalDialog.component.tsx
  src/components/common/AlertModalDialog/AlertModalDialog.component.tsx
  src/components/common/ModalViewer/ModalViewer.component.tsx
  src/components/common/ModalWrapper/ModalWrapper.component.tsx
  src/pages/ApplicationFormDetail/ApplicationFormDetail.page.tsx
  src/pages/CreateApplicationForm/CreateApplicationForm.page.tsx
  src/pages/UpdateApplicationForm/UpdateApplicationForm.page.tsx
Labels: bug, feature

#100 Logout 기능 추가
  .github/workflows/ci.yaml
  src/App.tsx
  src/assets/svg/logout-16.svg
  src/components/common/Header/Header.component.tsx
  src/components/common/PopOver/PopOver.component.tsx
  src/components/common/PopOver/PopOver.stories.tsx
  src/components/common/PopOver/PopOver.styled.ts
  src/components/common/index.ts
Labels: feature

#103 QA 1차 대응 (v0.0.1) - dididy
  src/App.tsx
  src/assets/svg/bubble-arrow-up-16.svg
  src/components/ApplicationDetail/MessageListPanel/MessageListPanel.component.tsx
  src/components/ApplicationDetail/SmsSendModalDialog/SmsSendModalDialog.component.tsx
  src/components/common/ModalWrapper/ModalWrapper.component.tsx
  src/components/common/ModalWrapper/ModalWrapper.styled.ts
  src/components/common/PopOver/PopOver.component.tsx
  src/components/common/PopOver/PopOver.styled.ts
  src/pages/ApplicationDetailView/ApplicationDetailView.page.tsx
  src/pages/ApplicationFormDetail/ApplicationFormDetail.page.tsx
Labels: bug

#104 v0.0.1 QA이슈 1차 대응 - 경빈
  src/components/ApplicationForm/ApplicationFormItem/ApplicationFormItem.component.tsx
  src/components/ApplicationForm/ApplicationFormPreview/ApplicationFormPreview.component.tsx
  src/components/ApplicationForm/ApplicationFormPreview/ApplicationFormPreview.styled.ts
  src/components/common/Toast/Toast.styled.ts
  src/pages/CreateApplicationForm/CreateApplicationForm.page.tsx
  src/styles/themes/button.ts
  src/styles/themes/zIndex.ts
Labels: bug

#105 QA 1차 대응 (v0.0.1) - minsour
  src/components/common/SearchOptionBar/SearchOptionBar.component.tsx
  src/components/common/Table/Table.component.tsx
  src/components/common/Table/Table.styled.ts
  src/pages/ApplicationFormList/ApplicationFormList.page.tsx
  src/pages/ApplicationFormList/ApplicationFormList.styled.ts
  src/styles/themes/colors.ts
Labels: bug

#112 QA 3차 대응 (v0.0.1) - mango906
  src/components/ApplicationForm/ApplicationFormTemplate/ApplicationFormTemplate.component.tsx
Labels: bug

#114 Qa Release 0.0.1 -3차
  src/components/ApplicationForm/ApplicationFormTemplate/ApplicationFormTemplate.component.tsx
Labels: deploy
